# Generated by Django 3.1.2 on 2020-12-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20201228_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(blank=True, related_name='scopes', through='articles.ScopeToArticle', to='articles.Scope'),
        ),
        migrations.AlterField(
            model_name='scopetoarticle',
            name='is_main',
            field=models.BooleanField(verbose_name='Основной раздел'),
        ),
    ]
