# Generated by Django 3.1.2 on 2020-12-28 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20201228_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(blank=True, related_name='articles', through='articles.ScopeToArticle', to='articles.Scope'),
        ),
        migrations.AlterField(
            model_name='scopetoarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_article', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='scopetoarticle',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_topic', to='articles.scope'),
        ),
    ]
